In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.__version__

'1.19.5'

In [ ]:
pd.__version__

'1.1.5'

In [ ]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2021-09-11 17:45:20--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv.2’

data.csv.2          100%[===================>]   1.41M  --.-KB/s    in 0.01s

2021-09-11 17:45:20 (139 MB/s) - ‘data.csv.2’ saved [1475504/1475504]

In [ ]:
df = pd.read_csv('data.csv')

In [ ]:
df.head()

  Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]

In [ ]:
print(f"The average price for BMW is {round(df[df.Make=='BMW'].MSRP.mean(),2)}")

The average price for BMW is 61546.76

In [ ]:
print(f"There are {df[df.Year>=2015]['Engine HP'].isnull().sum()} null values for 'Engine HP'")

There are 51 null values for 'Engine HP'

In [ ]:
print( f"The average horse power for cars made in 2015 and later is {round(df['Engine HP'].mean(),0)}")

The average horse power for cars made in 2015 and later is 249.0

In [ ]:
df['Engine HP'].fillna(df['Engine HP'].mean(), inplace=True)

In [ ]:
print( f"The average horse power for cars made in 2015 and later (after filling nulls) is {round(df['Engine HP'].mean(),0)}")

The average horse power for cars made in 2015 and later (after filling nulls) is 249.0

In [ ]:
df.head(2)

  Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650

[2 rows x 16 columns]

In [ ]:
df[df.Make == "Rolls-Royce"]

              Make                   Model  Year  ... city mpg  Popularity    MSRP
2921   Rolls-Royce                Corniche  2001  ...       10          86  359990
3505   Rolls-Royce                    Dawn  2016  ...       12          86  335000
5275   Rolls-Royce         Ghost Series II  2015  ...       13          86  286750
5276   Rolls-Royce         Ghost Series II  2015  ...       13          86  319400
5277   Rolls-Royce         Ghost Series II  2016  ...       13          86  295850
5278   Rolls-Royce         Ghost Series II  2016  ...       13          86  329325
5279   Rolls-Royce                   Ghost  2012  ...       13          86  250000
5280   Rolls-Royce                   Ghost  2012  ...       13          86  290000
5281   Rolls-Royce                   Ghost  2013  ...       13          86  296000
5282   Rolls-Royce                   Ghost  2013  ...       13          86  256650
5283   Rolls-Royce                   Ghost  2014  ...       13          86  263200
5284   Rolls-Royce                   Ghost  2014  ...       13          86  303300
7443   Rolls-Royce               Park Ward  2001  ...       11          86  259900
7444   Rolls-Royce               Park Ward  2002  ...       11          86  262990
7553   Rolls-Royce           Phantom Coupe  2014  ...       11          86  433550
7554   Rolls-Royce           Phantom Coupe  2015  ...       11          86  438325
7555   Rolls-Royce           Phantom Coupe  2016  ...       11          86  449525
7556   Rolls-Royce  Phantom Drophead Coupe  2014  ...       11          86  474600
7557   Rolls-Royce  Phantom Drophead Coupe  2015  ...       11          86  479775
7558   Rolls-Royce  Phantom Drophead Coupe  2016  ...       11          86  492000
7559   Rolls-Royce                 Phantom  2014  ...       11          86  402940
7560   Rolls-Royce                 Phantom  2014  ...       11          86  474990
7561   Rolls-Royce                 Phantom  2015  ...       11          86  407400
7562   Rolls-Royce                 Phantom  2015  ...       11          86  480175
7563   Rolls-Royce                 Phantom  2016  ...       11          86  417825
7564   Rolls-Royce                 Phantom  2016  ...       11          86  492425
9431   Rolls-Royce           Silver Seraph  2001  ...       11          86  219900
9432   Rolls-Royce           Silver Seraph  2002  ...       11          86  229990
11448  Rolls-Royce                  Wraith  2014  ...       13          86  284900
11449  Rolls-Royce                  Wraith  2015  ...       13          86  294025
11450  Rolls-Royce                  Wraith  2016  ...       13          86  304350

[31 rows x 16 columns]

In [ ]:
df[["Engine HP", "Engine Cylinders", "highway MPG"]]

       Engine HP  Engine Cylinders  highway MPG
0          335.0               6.0           26
1          300.0               6.0           28
2          300.0               6.0           28
3          230.0               6.0           28
4          230.0               6.0           28
...          ...               ...          ...
11909      300.0               6.0           23
11910      300.0               6.0           23
11911      300.0               6.0           23
11912      300.0               6.0           23
11913      221.0               6.0           26

[11914 rows x 3 columns]

In [ ]:
df[df.Make == "Rolls-Royce"][["Engine HP", "Engine Cylinders", "highway MPG"]]

       Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [ ]:
df[df.Make == "Rolls-Royce"][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()

       Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [ ]:
X = df[df.Make == "Rolls-Royce"][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates().values

In [ ]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [ ]:
XTX = (X.T).dot(X)
print("The inner product of matrix 'X' with itself is: \n")
XTX

The inner product of matrix 'X' with itself is:

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [ ]:
print("The inverse of 'XTX' is: \n")
np.linalg.inv(XTX)

The inverse of 'XTX' is:

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [ ]:
print("The sum of the elements of (XTX)^-1 is: \n")
np.linalg.inv(XTX).sum()

The sum of the elements of (XTX)^-1 is:

0.032212320677486125

In [ ]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

## (X<sup>T</sup>X)<sup>-1</sup>X<sup>T</sup>y = w

In [ ]:
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

In [ ]:
print(f"The first weight is: {w[0]}")

The first weight is: 0.19989598183188978

In [ ]:
w

array([ 0.19989598, 31.02612262, 31.65378877])